apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: nginx
    name: nginx-deployment
spec:
    replicas: 1
    selector:
        matchlabels:
            app: nginx
        spec:
            container:
            - image: nginx
              name: nginx